#!/bin/bash
# Build the static Mirage Season 1 archive into .deploy/ for Cloudflare Pages.
#
#   ./build-archive.sh
#   npx wrangler pages deploy .deploy --project-name=mirage-season1 --commit-dirty=true
#
# Mirage originally ran on Express (server.js), which served several paths from a
# single file. Pages is static, so those aliases are reproduced here as real files.
# season1.html declares <link rel="canonical"> pointing at /case-study, so that path
# MUST exist or the deployed archive advertises a canonical URL that 404s. The
# slide-18 QR code in presentation.html encodes the same URL.
#
# Express route            -> static file staged here
#   /                      -> index.html            (archive at root)
#   /season1.html          -> season1.html
#   /case-study            -> case-study.html       (CANONICAL — see above)
#   /mirage                -> mirage.html           (brand-path alias)
#   /archive/internal      -> archive/internal.html
#   /archive/behind-the-scenes -> archive/behind-the-scenes.html
#
# Deliberately NOT staged: app.html, admin.html (the live app and its dashboard).
#
# All third-party runtime dependencies were vendored into public/vendor/ on
# 2026-08-14 (Reveal.js 5.1.0, qrcodejs 1.0.0, Google Fonts, the hero MP3).
# The archive makes zero external requests; keep it that way.
set -euo pipefail
cd "$(dirname "$0")"
STAGE=.deploy

rm -rf "$STAGE" && mkdir -p "$STAGE/archive"

# season1.html is the archive; Express served it at four different paths.
cp public/season1.html          "$STAGE/season1.html"
cp public/season1.html          "$STAGE/index.html"
cp public/season1.html          "$STAGE/case-study.html"
cp public/season1.html          "$STAGE/mirage.html"

cp public/presentation.html     "$STAGE/"
cp public/farewell.html         "$STAGE/"

# internal.html carries its own noindex,nofollow; Express served it at two paths.
cp public/archive/internal.html "$STAGE/archive/internal.html"
cp public/archive/internal.html "$STAGE/archive/behind-the-scenes.html"

cp -R public/archive/screenshots "$STAGE/archive/"
cp -R public/vendor              "$STAGE/vendor"
cp public/favicon.svg public/icon-192.svg public/icon-512.svg public/apple-touch-icon.svg "$STAGE/" 2>/dev/null || true

# og:image target. Every page points at /og-card.png; without it, Pages' no-404
# fallback serves 76KB of HTML under an image URL and every social card breaks.
cp public/og-card.png "$STAGE/"

# 404.html is REQUIRED, not decorative. With no 404.html, Cloudflare Pages serves
# index.html with HTTP 200 for every unmatched path — /eat, /og-card.png and
# /anything-at-all all returned 200. That makes a status-code sweep meaningless
# and hands crawlers infinite duplicate copies of the archive.
cp public/404.html "$STAGE/"

# robots.txt, sitemap.xml and llms.txt were generated by Express routes that the
# static archive does not have. They ship as real files now. Do NOT regenerate
# robots.txt inline — an earlier version of this script overwrote the real 455-byte
# file with two lines, silently dropping the Disallow on the internal appendix and
# the AI-crawler allowlist.
cp public/robots.txt public/sitemap.xml public/llms.txt "$STAGE/"

# Guard: the live app and admin dashboard must never reach the public archive.
leaked=$(find "$STAGE" \( -name "app.html" -o -name "admin*.html" -o -name "eat.html" \
                        -o -name "series.html" -o -name "sponsors.html" \) -print)
[ -z "$leaked" ] || { echo "FATAL: app/admin leaked into staging:"; echo "$leaked"; exit 1; }

# Guard: the archive must stay sealed.
#
# This is an ALLOWLIST tripwire, not a blocklist. An earlier version listed the
# hosts to ban and scoped itself to --include="*.html"; it therefore reported the
# archive sealed while all four SVG icons were still @import-ing Google Fonts,
# which fired on every direct load of /favicon.svg. Enumerating what is forbidden
# only ever catches what you have already met. This fails on anything NEW instead,
# and it reads every text file in the archive, not just the HTML.
ALLOWED_HOSTS="mirage.sunshine.fm sunshine.fm www.sunshine.fm
www.youtube.com youtube.com bsky.app kesq.com
www.w3.org schema.org www.sitemaps.org
revealjs.com hakim.se marked.js.org github.com meyerweb.com"
# Why each is permitted:
#   *.sunshine.fm            self-reference — canonical, og:url, outbound
#   youtube.com              the archive page's video embeds; genuinely remote by nature
#   bsky.app, kesq.com       ordinary outbound links, never fetched
#   w3.org, schema.org,      xmlns and JSON-LD @context identifiers, never fetched
#   www.sitemaps.org         (the last is sitemap.xml's urlset namespace)
#   revealjs.com, hakim.se,  hosts NAMED inside vendored library license comments
#   marked.js.org,           (reveal.js, marked, the Meyer CSS reset). Not fetched.
#   github.com, meyerweb.com
# NOTE: sed -E, not a bare \? — BSD/macOS sed treats GNU's \? literally, which
# silently leaves the scheme attached and makes every host fail the allowlist.
found=$(find "$STAGE" -type f ! -name '*.woff2' ! -name '*.png' ! -name '*.mp3' -exec \
          grep -ohE "https?://[a-zA-Z0-9.-]+" {} + 2>/dev/null | sed -E 's|https?://||' | sort -u)
unexpected=""
for h in $found; do
  echo "$ALLOWED_HOSTS" | tr ' ' '\n' | grep -qx "$h" || unexpected="$unexpected $h"
done
[ -z "$unexpected" ] || {
  echo "FATAL: unrecognised external host(s) in the archive:$unexpected"
  echo "       If one is legitimately fetched, vendor it. If it is only NAMED"
  echo "       (a license comment, a namespace), add it to ALLOWED_HOSTS above."
  exit 1
}

# Guard: no visitor tracking. The archive collects nothing — no beacon to the dead
# Express API, no persistent device id, no third-party pixel. All file types.
#
# HTML comments are stripped before matching. Each removal is recorded in a comment
# that necessarily quotes the call it removed ("It fired fbq('init', ...)"), and an
# earlier version of this guard flagged its own documentation. Code inside an HTML
# comment cannot execute, so stripping them costs no coverage — it only separates
# a MENTION of tracking from a USE of it.
tracking=$(find "$STAGE" -type f ! -name '*.woff2' ! -name '*.png' ! -name '*.mp3' | while read -r f; do
  perl -0777 -pe 's/<!--.*?-->//gs' "$f" 2>/dev/null \
    | grep -qE "fetch\('/api/analytics|fbq\(|localStorage\.setItem\('mirage_session" && echo "$f"
done || true)
# NOTE: `|| true` is load-bearing. The loop's exit status is the last grep -q, which
# returns 1 when it finds NOTHING — the passing case. Under `set -e` that non-zero
# command substitution aborts the build silently, with no FATAL and no staged output.
[ -z "$tracking" ] || { echo "FATAL: visitor tracking reintroduced in:"; echo "$tracking"; exit 1; }

echo "staged $(find "$STAGE" -type f | wc -l | tr -d ' ') files, $(du -sh "$STAGE" | cut -f1) — sealed, no app/admin"
